{{- define "templates.service" -}}
{{- $templates := dict "Values" .Values.templates -}}
{{- $noTemplates := omit .Values "templates" -}}
{{- $overrides := dict "Values" $noTemplates -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $templates -}}

{{- if or (.Values.service.enabled) (eq .Values.metrics.kind "ServiceMonitor") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "templates.fullname" . }}
  labels:
    {{- include "templates.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if eq .Values.service.type "ClusterIP" }}
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  {{- else }}
  type: {{ default "ClusterIP" .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- end }}
  {{- end }}
  ports:
    {{- if .Values.service }}
    - port: {{ .Values.service.port }}
      targetPort: {{ default "http" .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- end }}
    {{- if and (.Values.metrics.enabled) (eq .Values.metrics.kind "ServiceMonitor") }}
    {{- range .Values.metrics.endpoints }}
    - port: {{ .port | default "4040" }}
      targetPort: {{ .targetPort | default "4040" }}
      protocol: TCP
      name: {{ .name | default "metrics" }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "templates.selectorLabels" . | nindent 4 }}

{{- end -}}
{{- end -}}
{{- end -}}
